"use strict";

/**
 * Query encoding used to request specific data fields from the Yahoo API.
 */

module.exports = {
  "a00": "ask price",
  "b00": "bid price",
  "g00": "day range low",
  "h00": "day range high",
  "j10": "market cap",
  "v00": "volume",
  "a50": "ask size",
  "b60": "bid size",
  "b30": "ecn bid",
  "o50": "ecn bid size",
  "z03": "ecn ext hr bid",
  "z04": "ecn ext hr bid size",
  "b20": "ecn ask",
  "o40": "ecn ask size",
  "z05": "ecn ext hr ask",
  "z07": "ecn ext hr ask size",
  "h01": "ecn day high",
  "g01": "ecn day low",
  "h02": "ecn ext hr day high",
  "g11": "ecn ext hr day low",
  "t10": "last trade time, will be in unix epoch format",
  "t50": "ecnQuote/last/time",
  "t51": "ecn ext hour time",
  "t53": "RTQuote/last/time",
  "t54": "RTExthourQuote/last/time",
  "l10": "last trade",
  "l90": "ecnQuote/last/value",
  "l91": "ecn ext hour price",
  "l84": "RTQuote/last/value",
  "l86": "RTExthourQuote/last/value",
  "c10": "quote/change/absolute",
  "c81": "ecnQuote/afterHourChange/absolute",
  "c60": "ecnQuote/change/absolute",
  "z02": "ecn ext hour change",
  "z08": "ecn ext hour change",
  "c63": "RTQuote/change/absolute",
  "c85": "RTExthourQuote/afterHourChange/absolute",
  "c64": "RTExthourQuote/change/absolute",
  "p20": "quote/change/percent",
  "c82": "ecnQuote/afterHourChange/percent",
  "p40": "ecnQuote/change/percent",
  "p41": "ecn ext hour percent change",
  "z09": "ecn ext hour percent change",
  "p43": "RTQuote/change/percent",
  "c86": "RTExtHourQuote/afterHourChange/percent",
  "p44": "RTExtHourQuote/change/percent",
};